# Welcome to Jekyll!

# Website settings
title: "Kraken"
description: "Utsav Mangal,blog and portofolio"
keywords: "Utsav,Mangal,blog,programming"

baseurl: "/"
url: "http://www.mangalutsav.xyz"
# url: "http://127.0.0.1:4000"

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# author
author:
  name: 'Utsav'
  first_name: 'Utsav'
  last_name: 'Mangal'
  email: 'mangalutsav1@gmail.com'
  facebook_username: 'Mangalutsav'
  github_username: 'Mangalutsav'
  head_img: 'static/img/landing/Utsav.jpg'

# landing page
landing:
  home: 'Home'
  about: 'About'
  career: 'Career'
  skills: 'Skills'
  projects: 'Project'
  blog: 'Blog'

# my projects
project:
  SigIntChecker:
    name: 'SigIntChecker'
    url: '/Mangalutsav/Check_SIGINT'
    img: 'static/img/landing/SigIntChecker.png'
  Stroom:
    name: 'Stroom'
    url: '/Hareshkh/Stroom'
    img: 'static/img/landing/Stroom.jpg'
  Youtoo:
    name: 'Youtoo'
    url: '/Mangalutsav/Youtoo'
    img: 'static/img/landing/Youtoo.png'
  Yolog:
    name: 'Yolog'
    url: '/Karandesai-96/Yolog'
    img: 'static/img/landing/yolog.jpg'

# blog index
index:
  home: 'Home'
  # python: 'Python'
  # linux: 'Linux'
  # JS: 'JS'
  # database: 'Database'
  # life: 'Life'

# comment
disqus:
  name: Kraken
  public_key: FTvHZuuS0XcH4XZHNWzASYpEPQ2VHnGrtk7NRPNKMpKnjZaSaRDmVImMZ4HLsPnF

# google analytics
ga:
  id: UA-77166641-2

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
